---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```


## Load in the FAS Litters Data
```{r}
litters_df=read_csv("./data_import_examples/FAS_litters.csv")
litters_df=janitor::clean_names(litters_df)
```

## `select`
choose some columns and not others.
```{r}
select(litters_df,group, litter_number)#I only want to keep the columns of "group" and "litter_number"
```

```{r}
select(litters_df,group:gd_of_birth)#I can select the range of columns, so in this case I keep the columns from group to gd_of_birth
```

```{r}
select(litters_df,-litter_number)#we drop the litter_number column by add a "-"
```

Remaining columns...
```{r}
select(litters_df,GROUP = group, LITTER_NUmBer = litter_number)#We will rename these two columns but only keep these two columns
```
```{r}
rename(litters_df,GROUP = group, LITTER_NUmBer = litter_number)#We can rename these two columns but keep the rest of the columns at the same time
```

?select_helpers
```{r}
select(litters_df,starts_with("gd"))#select the variable that have gd
```
```{r}
select(litters_df,litter_number,everything())#put the litter_number to the first column, and keep everything
```

```{r}
relocate(litters_df,litter_number)#relocatet litter_number to the first column, and not changing eveything else
```

##`filter`
```{r}
filter(litters_df, gd0_weight < 22) #only keep the people with gd0_weight less than 22
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth==20)#we use double = is because we are not asking the variable to go into 20, we are just asking are these two thing equal to each others
```

```{r}
filter(litters_df, !(gd_of_birth==20))#show the people that have gd_of_birth is not equal to 20
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth==20)
```

```{r}
filter(litters_df, group =="Mod8") #only keeps the rows with Mod8
```

```{r}
filter(litters_df, group %in% c("Mod8","Mod7")) #keep the groups either Mod8 or Mod7
```

##`mutate`
```{r}
mutate(
  litters_df,
  wt_gain = as.numeric(gd18_weight) - as.numeric(gd0_weight), #we can create a new variable through mutate
  #I added the as.numeric as only numeric numbers can minus each others, there was a categorical number before
  group = str_to_lower(group))#at the same time we can also adjust the existing variable "group" to lower case
```
 
 
## `arrange`
putting things in order
```{r}
arrange(litters_df,pups_born_alive) #arrange the dataset by order of pups_born_alive
```

we can also write arrange(litters_df, pups_born_alive, gd0_weight)
it arrange the order for pups_born_alive first, and then gd0_weight





