---
title: "Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse)
```


## `pivot_longer`

load the PULSE data 

```{r}
pulse_data=
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

wide format to LONG format..
originally it is the id with different weights(readable version), but we want to change it to different weight as the rows(one id might appear many times) (tidy version)- which is easier to analyze
```{r}
pulse_data_tidy = 
    pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, #specifiy the column range
    names_to = "visit", #where those column go into, so we are now creating a new column named visit for those original weight columns
    names_prefix = "bdi_score_", #delete this part of the name, make it clearer
    values_to = "bdi" #we put the values for different weights into this new columns
  )
```

rewrite, combine, and extend (to add a mutate)
```{r}
pulse_data = 
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit", 
    names_prefix = "bdi_score_", 
    values_to = "bdi" 
  ) %>% 
  relocate(id,visit) %>%  #put id and visit to the first or second columns
  mutate(visit = recode(visit , "bl" = "00m") )  #change this bl variable into 00m
```

## `pivot wider`
Make up some data!

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment","placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4,8,3.5,4)
  )#tibble is for we making up data by ourselves
analysis_result %>% 
  pivot_wider(
    names_from = "time", #make the "pre" and "post" from time as the column variables
    values_from = "mean" #make the "treatment" and "placebo" from group as the row variables
  )
```

